import type { GameStatus } from './points.ts';
export type Platform = 'espn' | 'sleeper';
export type Player = {
  id: string;
  key: string;
  name: string;
  position: string;
  team: string;
  eligible: string[];
  slot: string | null;
  projection: number | null;
  actual: number | null;
  partial: boolean;
  injury: string;
  bye: boolean;
  kickoff: number | null;
  gameStatus: GameStatus;
  opponent: string;
  locked: boolean | null;
  lockReason?: string;
  autoSubLock?: true;
  reserve: boolean;
  taxi: boolean;
};
export type Slot = { id: string; key: string; label: string };
export type Standing = {
  id: string;
  name: string;
  wins: number;
  losses: number;
  ties: number;
  points: number;
  mine: boolean;
};
export type League = {
  id: string;
  platform: Platform;
  autoSubs?: boolean;
  name: string;
  teamName: string;
  url: string;
  status: string;
  week: number;
  currentWeek: number;
  season: number;
  fetchedAt: string;
  scoring: string;
  source: string;
  players: Player[];
  slots: Slot[];
  standings: Standing[];
  record: string;
  actual: number | null;
  matchupProjection: number | null;
  opponent: {
    id?: string;
    players?: Player[];
    rosterVerified?: boolean;
    name: string;
    actual: number | null;
    projection: number | null;
  } | null;
  warnings: string[];
  error?: string;
  stale?: boolean;
};
export type Dashboard = {
  season: number;
  week: number;
  currentWeek: number;
  fetchedAt: string;
  leagues: League[];
  warnings: string[];
};
export type Assignment = {
  slot: Slot;
  current: Player | null;
  recommended: Player | null;
  locked: boolean;
};
export type Analysis = {
  assignments: Assignment[];
  currentTotal: number | null;
  recommendedTotal: number | null;
  gain: number | null;
  changes: Player[];
  removed: Player[];
  issues: { player: Player | null; slot: string; reason: string }[];
  review: {
    player: Player;
    slot: string;
    kind: 'projection' | 'actual' | 'game-status' | 'lock';
    reason: string;
  }[];
  coverage: { starterScores: number; starterSlots: number };
  complete: boolean;
  enabled: boolean;
  reasons: string[];
};
